[package]
name = "devoxx-rust"
version = "0.1.0"
authors = ["Clement Delafargue <clement@delafargue.name>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
